spring:
  datasource:
    url: jdbc:mysql://localhost:3306/banco_use
    username: root
    password: 3325157
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false